<a href="https://colab.research.google.com/github/DanielCataneo/Python_DataAnalysesProjects/blob/main/Course%20Notation/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**CRIANDO ARRAYS COM NUMPY**



In [ ]:
import sys
import numpy as np

a = [1,2,3,4,5]
b = np.array([1,2,3,4,5])

print(a)

print()
print('Numpy')
print(b)

[1, 2, 3, 4, 5]

Numpy
[1 2 3 4 5]


In [ ]:
# Verificando Tamanho de duas arrays

sys.getsizeof(a)


104

In [ ]:
# Numpy muito mais leve
b.nbytes

40

**CRIANDO ARRAYS 1D 2D 3D**

In [ ]:
# 1D

D1 = np.array([1,2,3])
print(D1)

# Dimensoes
D1.ndim

[1 2 3]


1

In [ ]:
# 2D

D2 = np.array([[1,2,3],[4,5,6]])
print(D2)

# Formato
D2.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [ ]:
# 3D
                  # UM ARRAY            OUTRO ARRAY
D3 = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])
print(D3)

# Formato
D3.shape

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


(2, 2, 3)

**SOMANDO ARRAYS**

In [ ]:
# Listas
a = [2,3,4]
b = [2,3,4]

# Apenas concatena
result = a + b
print(result)

# Numpy Arrays
a = np.array([1,2,3])
b = np.array([1,2,3])

# Soma os indexs
result = a + b
print(result)

# Escrita alternativa
result = np.add(a , b)

[2, 3, 4, 2, 3, 4]
[2 4 6]


**SELECIONANDO ITENS EM ARRAYS**

In [ ]:
A = np.array([[2,3,'R$19.90',5], [6,7,'Apple',9]])

print(A)

[['2' '3' 'R$19.90' '5']
 ['6' '7' 'Apple' '9']]


In [ ]:
# Array[row,column]
A[1,2]

np.str_('Apple')

In [ ]:
# Somente a primeira linha
A[:,2]

array(['R$19.90', 'Apple'], dtype='<U21')